### ISSUE TITLE
Request a new tag or release for the latest code

### ISSUE THREAD

**Issue by caojen** [barbashov/iso639-3#3]
Hi, I am wondering if you could simply add a tag or publish a new release like `v1.0.0` on master branch.

This will be helpful to make the import more beautiful, from 
```
github.com/barbashov/iso639-3 v0.0.0-20211020172741-1f4ffb2d8d1c
```
to
```
github.com/barbashov/iso639-3 v1.0.0
```

**Comment by caojen** [comment]
@barbashov

**Comment by barbashov** [comment]
Here you go https://github.com/barbashov/iso639-3/tree/v1.0.0

**Comment by caojen** [comment]
> Here you go https://github.com/barbashov/iso639-3/tree/v1.0.0

Awesome! Thanks so much!
